version: 0.2
#
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ghost:latest .
      - docker tag ghost:latest  $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/ghost:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/ghost:latest
      - printf '[{"name":"ghost","imageUri":"{$ACCOUNT_ID}.dkr.ecr.{$REGION}.amazonaws.com/ghost:latest"}]' > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
